#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.
*/
#ifndef _CFFI_USE_EMBEDDING
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47

#define _CFFI__NUM_PRIM         48
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _CFFI_NUM_EXPORTS 26

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "apriltag_interface.h"

void apriltag_init(
  apriltag_detector_t* td,
  float decimate,
  float sigma,
  int refine_edges,
  int refine_decode,
  int refine_pose
) {
  apriltag_family_t *tf = tag36h11_create();
  apriltag_detector_add_family(td, tf);
  td->quad_decimate = decimate;
  td->quad_sigma = sigma;
  td->refine_edges = refine_edges;
  td->refine_decode = refine_decode;
  td->refine_pose = refine_pose;
}


struct apriltag_detection *zarray_get_detection(const zarray_t *za, int idx) {
    struct apriltag_detection *detection = malloc(sizeof(apriltag_detection_t));
    zarray_get(za, idx, &detection);
    return detection;
}

void destroy_detection(struct apriltag_detection * p) {
    free(p);
}

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 16), // apriltag_detection_t *()(zarray_t const *, int)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 61), // zarray_t const *
/*  2 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION, 19), // image_u8_t *()(unsigned int, unsigned int)
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8), // unsigned int
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 19), // image_u8_t *()(unsigned int, unsigned int, unsigned int)
/*  9 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/* 10 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 22), // void *()(void)
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(apriltag_detection_t *)
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // apriltag_detection_t *
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(image_u8_t *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 53), // image_u8_t *
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(void *)
/* 22 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // void *
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 24 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(void *, float, float, int, int, int)
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 22),
/* 26 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 27 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 28 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 30 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 31 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(zarray_t *)
/* 33 */ _CFFI_OP(_CFFI_OP_POINTER, 61), // zarray_t *
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(zarray_t const *, int, void *)
/* 36 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 22),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION, 33), // zarray_t *()(void *, image_u8_t *)
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 22),
/* 42 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 44 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // apriltag_detection_t
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 46), // char *
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 47 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 48 */ _CFFI_OP(_CFFI_OP_ARRAY, 47), // double[2]
/* 49 */ (_cffi_opcode_t)(2),
/* 50 */ _CFFI_OP(_CFFI_OP_ARRAY, 48), // double[4][2]
/* 51 */ (_cffi_opcode_t)(4),
/* 52 */ _CFFI_OP(_CFFI_OP_OPEN_ARRAY, 47), // double[]
/* 53 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // image_u8_t
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21), // int32_t
/* 55 */ _CFFI_OP(_CFFI_OP_POINTER, 56), // matd_t *
/* 56 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // matd_t
/* 57 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 59), // uint8_t *
/* 59 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 60 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
/* 61 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // zarray_t
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_matd_t(matd_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->nrows) | 0);  /* check that 'matd_t.nrows' is an integer */
  (void)((p->ncols) | 0);  /* check that 'matd_t.ncols' is an integer */
  { double *tmp = &p->data[0]; (void)tmp; }
}
struct _cffi_align_typedef_matd_t { char x; matd_t y; };

static void _cffi_d_apriltag_detections_destroy(zarray_t * x0)
{
  apriltag_detections_destroy(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_apriltag_detections_destroy(PyObject *self, PyObject *arg0)
{
  zarray_t * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(33), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (zarray_t *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(33), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { apriltag_detections_destroy(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_apriltag_detections_destroy _cffi_d_apriltag_detections_destroy
#endif

static void * _cffi_d_apriltag_detector_create(void)
{
  return apriltag_detector_create();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_apriltag_detector_create(PyObject *self, PyObject *noarg)
{
  void * result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = apriltag_detector_create(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(22));
}
#else
#  define _cffi_f_apriltag_detector_create _cffi_d_apriltag_detector_create
#endif

static void _cffi_d_apriltag_detector_destroy(void * x0)
{
  apriltag_detector_destroy(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_apriltag_detector_destroy(PyObject *self, PyObject *arg0)
{
  void * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(22), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (void *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(22), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { apriltag_detector_destroy(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_apriltag_detector_destroy _cffi_d_apriltag_detector_destroy
#endif

static zarray_t * _cffi_d_apriltag_detector_detect(void * x0, image_u8_t * x1)
{
  return apriltag_detector_detect(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_apriltag_detector_detect(PyObject *self, PyObject *args)
{
  void * x0;
  image_u8_t * x1;
  Py_ssize_t datasize;
  zarray_t * result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "apriltag_detector_detect", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(22), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (void *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(22), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (image_u8_t *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(19), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = apriltag_detector_detect(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(33));
}
#else
#  define _cffi_f_apriltag_detector_detect _cffi_d_apriltag_detector_detect
#endif

static void _cffi_d_apriltag_init(void * x0, float x1, float x2, int x3, int x4, int x5)
{
  apriltag_init(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_apriltag_init(PyObject *self, PyObject *args)
{
  void * x0;
  float x1;
  float x2;
  int x3;
  int x4;
  int x5;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "apriltag_init", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(22), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (void *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(22), arg0) < 0)
      return NULL;
  }

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  x2 = (float)_cffi_to_c_float(arg2);
  if (x2 == (float)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, int);
  if (x3 == (int)-1 && PyErr_Occurred())
    return NULL;

  x4 = _cffi_to_c_int(arg4, int);
  if (x4 == (int)-1 && PyErr_Occurred())
    return NULL;

  x5 = _cffi_to_c_int(arg5, int);
  if (x5 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { apriltag_init(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_apriltag_init _cffi_d_apriltag_init
#endif

static void _cffi_d_destroy_detection(apriltag_detection_t * x0)
{
  destroy_detection(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_destroy_detection(PyObject *self, PyObject *arg0)
{
  apriltag_detection_t * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (apriltag_detection_t *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(16), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { destroy_detection(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_destroy_detection _cffi_d_destroy_detection
#endif

static image_u8_t * _cffi_d_image_u8_create(unsigned int x0, unsigned int x1)
{
  return image_u8_create(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_image_u8_create(PyObject *self, PyObject *args)
{
  unsigned int x0;
  unsigned int x1;
  image_u8_t * result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "image_u8_create", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, unsigned int);
  if (x0 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, unsigned int);
  if (x1 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = image_u8_create(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(19));
}
#else
#  define _cffi_f_image_u8_create _cffi_d_image_u8_create
#endif

static image_u8_t * _cffi_d_image_u8_create_stride(unsigned int x0, unsigned int x1, unsigned int x2)
{
  return image_u8_create_stride(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_image_u8_create_stride(PyObject *self, PyObject *args)
{
  unsigned int x0;
  unsigned int x1;
  unsigned int x2;
  image_u8_t * result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "image_u8_create_stride", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  x0 = _cffi_to_c_int(arg0, unsigned int);
  if (x0 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, unsigned int);
  if (x1 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, unsigned int);
  if (x2 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = image_u8_create_stride(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(19));
}
#else
#  define _cffi_f_image_u8_create_stride _cffi_d_image_u8_create_stride
#endif

static void _cffi_d_image_u8_destroy(image_u8_t * x0)
{
  image_u8_destroy(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_image_u8_destroy(PyObject *self, PyObject *arg0)
{
  image_u8_t * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (image_u8_t *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(19), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { image_u8_destroy(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_image_u8_destroy _cffi_d_image_u8_destroy
#endif

static void _cffi_d_zarray_destroy(zarray_t * x0)
{
  zarray_destroy(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_zarray_destroy(PyObject *self, PyObject *arg0)
{
  zarray_t * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(33), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (zarray_t *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(33), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { zarray_destroy(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_zarray_destroy _cffi_d_zarray_destroy
#endif

static void _cffi_d_zarray_get(zarray_t const * x0, int x1, void * x2)
{
  zarray_get(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_zarray_get(PyObject *self, PyObject *args)
{
  zarray_t const * x0;
  int x1;
  void * x2;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "zarray_get", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (zarray_t const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(22), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (void *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(22), arg2) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { zarray_get(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_zarray_get _cffi_d_zarray_get
#endif

static apriltag_detection_t * _cffi_d_zarray_get_detection(zarray_t const * x0, int x1)
{
  return zarray_get_detection(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_zarray_get_detection(PyObject *self, PyObject *args)
{
  zarray_t const * x0;
  int x1;
  Py_ssize_t datasize;
  apriltag_detection_t * result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "zarray_get_detection", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (zarray_t const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = zarray_get_detection(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(16));
}
#else
#  define _cffi_f_zarray_get_detection _cffi_d_zarray_get_detection
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__apriltag_detection_t(apriltag_detection_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->family; (void)tmp; }
  (void)((p->id) | 0);  /* check that 'apriltag_detection_t.id' is an integer */
  (void)((p->hamming) | 0);  /* check that 'apriltag_detection_t.hamming' is an integer */
  { float *tmp = &p->goodness; (void)tmp; }
  { float *tmp = &p->decision_margin; (void)tmp; }
  { matd_t * *tmp = &p->H; (void)tmp; }
  { double(*tmp)[2] = &p->c; (void)tmp; }
  { double(*tmp)[4][2] = &p->p; (void)tmp; }
}
struct _cffi_align__apriltag_detection_t { char x; apriltag_detection_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__image_u8_t(image_u8_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->width) | 0);  /* check that 'image_u8_t.width' is an integer */
  (void)((p->height) | 0);  /* check that 'image_u8_t.height' is an integer */
  (void)((p->stride) | 0);  /* check that 'image_u8_t.stride' is an integer */
  { uint8_t * *tmp = &p->buf; (void)tmp; }
}
struct _cffi_align__image_u8_t { char x; image_u8_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__zarray_t(zarray_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->el_sz) | 0);  /* check that 'zarray_t.el_sz' is an integer */
  (void)((p->size) | 0);  /* check that 'zarray_t.size' is an integer */
  (void)((p->alloc) | 0);  /* check that 'zarray_t.alloc' is an integer */
  { char * *tmp = &p->data; (void)tmp; }
}
struct _cffi_align__zarray_t { char x; zarray_t y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "apriltag_detections_destroy", (void *)_cffi_f_apriltag_detections_destroy, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 32), (void *)_cffi_d_apriltag_detections_destroy },
  { "apriltag_detector_create", (void *)_cffi_f_apriltag_detector_create, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 13), (void *)_cffi_d_apriltag_detector_create },
  { "apriltag_detector_destroy", (void *)_cffi_f_apriltag_detector_destroy, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 21), (void *)_cffi_d_apriltag_detector_destroy },
  { "apriltag_detector_detect", (void *)_cffi_f_apriltag_detector_detect, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 40), (void *)_cffi_d_apriltag_detector_detect },
  { "apriltag_init", (void *)_cffi_f_apriltag_init, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 24), (void *)_cffi_d_apriltag_init },
  { "destroy_detection", (void *)_cffi_f_destroy_detection, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 15), (void *)_cffi_d_destroy_detection },
  { "image_u8_create", (void *)_cffi_f_image_u8_create, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 4), (void *)_cffi_d_image_u8_create },
  { "image_u8_create_stride", (void *)_cffi_f_image_u8_create_stride, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 8), (void *)_cffi_d_image_u8_create_stride },
  { "image_u8_destroy", (void *)_cffi_f_image_u8_destroy, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 18), (void *)_cffi_d_image_u8_destroy },
  { "zarray_destroy", (void *)_cffi_f_zarray_destroy, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 32), (void *)_cffi_d_zarray_destroy },
  { "zarray_get", (void *)_cffi_f_zarray_get, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 35), (void *)_cffi_d_zarray_get },
  { "zarray_get_detection", (void *)_cffi_f_zarray_get_detection, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_zarray_get_detection },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "nrows", offsetof(matd_t, nrows),
             sizeof(((matd_t *)0)->nrows),
             _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "ncols", offsetof(matd_t, ncols),
             sizeof(((matd_t *)0)->ncols),
             _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "data", offsetof(matd_t, data),
            (size_t)-1,
            _CFFI_OP(_CFFI_OP_NOOP, 52) },
  { "family", offsetof(apriltag_detection_t, family),
              sizeof(((apriltag_detection_t *)0)->family),
              _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "id", offsetof(apriltag_detection_t, id),
          sizeof(((apriltag_detection_t *)0)->id),
          _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "hamming", offsetof(apriltag_detection_t, hamming),
               sizeof(((apriltag_detection_t *)0)->hamming),
               _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "goodness", offsetof(apriltag_detection_t, goodness),
                sizeof(((apriltag_detection_t *)0)->goodness),
                _CFFI_OP(_CFFI_OP_NOOP, 26) },
  { "decision_margin", offsetof(apriltag_detection_t, decision_margin),
                       sizeof(((apriltag_detection_t *)0)->decision_margin),
                       _CFFI_OP(_CFFI_OP_NOOP, 26) },
  { "H", offsetof(apriltag_detection_t, H),
         sizeof(((apriltag_detection_t *)0)->H),
         _CFFI_OP(_CFFI_OP_NOOP, 55) },
  { "c", offsetof(apriltag_detection_t, c),
         sizeof(((apriltag_detection_t *)0)->c),
         _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "p", offsetof(apriltag_detection_t, p),
         sizeof(((apriltag_detection_t *)0)->p),
         _CFFI_OP(_CFFI_OP_NOOP, 50) },
  { "width", offsetof(image_u8_t, width),
             sizeof(((image_u8_t *)0)->width),
             _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "height", offsetof(image_u8_t, height),
              sizeof(((image_u8_t *)0)->height),
              _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "stride", offsetof(image_u8_t, stride),
              sizeof(((image_u8_t *)0)->stride),
              _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "buf", offsetof(image_u8_t, buf),
           sizeof(((image_u8_t *)0)->buf),
           _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "el_sz", offsetof(zarray_t, el_sz),
             sizeof(((zarray_t *)0)->el_sz),
             _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "size", offsetof(zarray_t, size),
            sizeof(((zarray_t *)0)->size),
            _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "alloc", offsetof(zarray_t, alloc),
             sizeof(((zarray_t *)0)->alloc),
             _CFFI_OP(_CFFI_OP_NOOP, 2) },
  { "data", offsetof(zarray_t, data),
            sizeof(((zarray_t *)0)->data),
            _CFFI_OP(_CFFI_OP_NOOP, 45) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$matd_t", 56, _CFFI_F_CHECK_FIELDS,
    sizeof(matd_t), offsetof(struct _cffi_align_typedef_matd_t, y), 0, 3 },
  { "apriltag_detection", 44, _CFFI_F_CHECK_FIELDS,
    sizeof(apriltag_detection_t), offsetof(struct _cffi_align__apriltag_detection_t, y), 3, 8 },
  { "image_u8", 53, _CFFI_F_CHECK_FIELDS,
    sizeof(image_u8_t), offsetof(struct _cffi_align__image_u8_t, y), 11, 4 },
  { "zarray", 61, _CFFI_F_CHECK_FIELDS,
    sizeof(zarray_t), offsetof(struct _cffi_align__zarray_t, y), 15, 4 },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "apriltag_detection_t", 44 },
  { "apriltag_detector_t", 60 },
  { "apriltag_family_t", 60 },
  { "image_u8_t", 53 },
  { "matd_t", 56 },
  { "zarray_t", 61 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  12,  /* num_globals */
  4,  /* num_struct_unions */
  0,  /* num_enums */
  6,  /* num_typenames */
  NULL,  /* no includes */
  62,  /* num_types */
  0,  /* flags */
};

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__apriltag(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__apriltag(void) { return NULL; }
#  else
     init_apriltag(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__apriltag(void)
{
  return _cffi_init("_apriltag", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_apriltag(void)
{
  _cffi_init("_apriltag", 0x2601, &_cffi_type_context);
}
#endif
